apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    spec:
      containers:
        - name: frontend
          image: dtsrhpprodscedspokeacr.azurecr.io/canada-disability-benefit/cdb-frontend:1.0.0
          envFrom:
            - configMapRef:
                name: frontend
            - secretRef:
                name: frontend
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PASSWORD
        - name: fluentd
          image: docker.io/fluentd:v1.16-1
          args: [--config, /etc/fluentd.conf]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: audit-logs
              mountPath: /logs
            - name: fluentd-conf
              mountPath: /etc/fluentd.conf
              subPath: fluentd.conf
      volumes:
        - name: fluentd-conf
          configMap:
            name: frontend-fluentd
