apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-disability-benefit
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: dev
      app.kubernetes.io/tier: nonprod
  # It is essential for this label (or at least one unique label per environment)
  # to be part of selectors to ensure they are applied correctly.
  - pairs:
      app.kubernetes.io/instance: dev
    includeSelectors: true
resources:
  - ../../base/frontend/
  - ./external-secrets.yaml
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments.yaml
configMapGenerator:
  - name: frontend
    behavior: create
    envs:
      - ./configs/frontend.conf
secretGenerator:
  - name: frontend
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true
