apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: frontend
          # Note: image tag should be pinned to a specific version in overlays
          image: dtsrhpdevscedacr.azurecr.io/canada-disability-benefit/cdb-frontend
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: audit-logs
              mountPath: /home/node/logs
      volumes:
        - name: audit-logs
          emptyDir: {}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
