apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-disability-benefit-portal
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-disability-benefit
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-prod-sced-rhp-spoke-aks
      app.kubernetes.io/environment: prod
      app.kubernetes.io/tier: prod
resources:
  - ../base/frontend/
  - ../base/fluentd-archiver/
  - ../base/maintenance/
  - ../base/redis/
  - ./external-secrets.yaml
  - ./hpas.yaml
  #
  # Note: to enable maintenance mode:
  #
  #   1. comment ./ingresses.yaml
  #   2. for full application maintenance, uncomment ./ingresses-maintenance.yaml
  #
  #
  - ./ingresses.yaml
  # - ./ingresses-maintenance.yaml
  # Note: for the maintenance page, see the maintenance configMapGenerator below
patches:
  - path: ./patches/deployments-frontend.yaml
  - path: ./patches/deployments-maintenance.yaml
  - path: ./patches/pvcs.yaml
  - path: ./patches/services.yaml
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - name: frontend
    behavior: create
    envs:
      - ./configs/frontend/config.conf
  - name: frontend-fluentd
    behavior: create
    files:
      - ./configs/frontend/fluentd.conf
  - name: redis
    behavior: merge
    files:
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
  - name: maintenance
    behavior: merge
    # TODO :: GjB :: this is a temporary override of the maintenance page HTML
    #                it should be removed when the letters are brought back online
    # TODO :: GjB :: I am commenting this out but leaving the updated 503 page in
    #                the project as a reference for future, similar deployments
    # files:
    #   - ./configs/maintenance/503.html
    literals:
      - startTimeEn=10:00pm EDT April 30, 2025
      - startTimeFr=30 avril 2025 à 22 h 00 HAE
      - endTimeEn=7:00am EDT May 1, 2025
      - endTimeFr=1 mai 2025 à 7 h 00 HAE
secretGenerator:
  - name: frontend
    behavior: create
    options:
      # disable suffix hash so it can effectively
      # be managed by external secrets operator
      disableNameSuffixHash: true