apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-disability-benefit
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: 
      app.kubernetes.io/environment: local
      app.kubernetes.io/tier: nonprod
  # It is essential for this label (or at least one unique label per environment)
  # to be part of selectors to ensure they are applied correctly.
  - pairs:
      app.kubernetes.io/instance: local
    includeSelectors: true
resources:
  - ../../base/frontend/
  - ./ingresses.yaml
  - ../../base/fluentd-archiver
patches:
  - path: ./patches/deployments.yaml
configMapGenerator:
  - name: frontend
    behavior: create
    envs:
      - ./configs/frontend.conf
configMapGenerator:
  - name: frontend
    behavior: merge
    envs:
      - ./configs/frontend.conf
  - name: frontend-fluentd
    behavior: create
    files:
      - ./configs/fluentd.conf
