apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: AUTH_CLIENT_PRIVATE_KEY
      remoteRef: { key: shared, property: AUTH_CLIENT_PRIVATE_KEY }
    - secretKey: AUTH_CLIENT_PUBLIC_KEY
      remoteRef: { key: shared, property: AUTH_CLIENT_PUBLIC_KEY }
    - secretKey: CCT_API_KEY
      remoteRef: { key: shared, property: CCT_API_KEY }
    - secretKey: DYNATRACE_API_KEY
      remoteRef: { key: shared, property: DYNATRACE_API_KEY }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: shared, property: SESSION_COOKIE_SECRET }
    - secretKey: INTEROP_API_SUBSCRIPTION_KEY
      remoteRef: { key: shared, property: INTEROP_API_SUBSCRIPTION_KEY }
  target:
    template:
      data:
        AUTH_CLIENT_PRIVATE_KEY: '{{ .AUTH_CLIENT_PRIVATE_KEY }}'
        AUTH_CLIENT_PUBLIC_KEY: '{{ .AUTH_CLIENT_PUBLIC_KEY }}'
        CCT_API_KEY: '{{ .CCT_API_KEY }}'
        INTEROP_API_SUBSCRIPTION_KEY: '{{ .INTEROP_API_SUBSCRIPTION_KEY }}'
        OTEL_AUTH_HEADER: 'Api-Token {{ .DYNATRACE_API_KEY }}'
        SESSION_COOKIE_SECRET: '{{ .SESSION_COOKIE_SECRET }}'
